name: test
on: [push, pull_request]
env:
  BUILD_ENV: test
  TEST_DATABASE_URL: postgresql://postgres:postgres@postgres:5432/express-test?sslmode=disable
jobs:
  test-linux:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}:master
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
        - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - run: make test
