name: Test
on: [push, pull_request]
on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install CMake and GCC
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake gcc
        
    - name: Run program-tests
      run: |
        make all
        ./program-tests
